[package]
name = "flowsurface"
version = "0.5.0"
edition = "2021"

[dependencies]
iced = { version = "0.14.0-dev", features = ["canvas", "tokio", "image", "advanced", "lazy"] }
iced_futures = "0.13.2"
chrono = "0.4.38"
tokio = { version = "1.41.1", features = ["full", "macros"] }
tokio-tungstenite = "0.21.0"
url = "2.5.3"
tokio-native-tls = "0.3.1"
base64 = "0.22.1"
native-tls = "0.2.12"
tungstenite = "0.21.0"
futures = "0.3.31"
futures-util = "0.3.31"
serde_json = "1.0.132"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["json"] }
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
bytes = "1.8.0"
sonic-rs = "0.3.17"
fastwebsockets = { version = "0.8.0", features = ["upgrade"] }
http-body-util = "0.1.2"
hyper = { version = "1", features = ["http1", "server", "client"] }
hyper-util = { version = "0.1.10", features = ["tokio"] }
tokio-rustls = "0.24.1"
webpki-roots = "0.23.1"
rustc-hash = "2.0.0"
fern = "0.6.2"
log = "0.4.22"
thiserror = "1.0.68"
ordered-float = "4.5.0"
regex = "1.11.1"
rust_decimal = "1.36.0"
uuid = { version = "1.11.0", features = ["v4"] }
zip = "2.2.1"
csv = "1.3.1"

[dependencies.async-tungstenite]
version = "0.25"
features = ["tokio-rustls-webpki-roots"]

[patch.crates-io]
iced = { git = "https://github.com/iced-rs/iced", rev = "ce4ee9323d31d7f346b1d775945f7629f3c5ab64" }